server:
  port: 9081

# JDBC Configuration
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mysql-ventalis-jp.alwaysdata.net/ventalis-jp_productsdb
    username: ***********
    password: ***********
# JPA Configuration

  jpa:
    database-platform: org.hibernate.dialect
    database: mysql
    hibernate:
      ddl-auto: none # other options : none, validate, update, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
    show-sql: true # to see sql commands

# SQL Initialisation
  sql:
    init:
      mode: always # never, embedded, always
      platform: mysql # specify the suffix of schema-{platform}.sql and data-{plateform}.sql files
