# MariaDB configuration for micro-products
server:
  port: 9081

# JDBC Configuration
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://**{database-url}**/ventalis-jp_productsdb
    username: ************
    password: ************

# JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect
    database: mysql
    hibernate:
      ddl-auto: update # other options : none, validate ##for production##, update, create-drop ##DNU: for the FIRST init ONLY##
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
    show-sql: true # to see sql commands

# SQL Initialisation
  sql:
    init:
      mode: never # never ##for production##, embedded, always ##DNU: for the FIRST init ONLY##
      platform: mysql # specify the suffix of schema-{platform}.sql and data-{plateform}.sql files
