# MariaDB configuration for micro-orders
server:
  port: 9082

# JDBC Configuration
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://**{yourDatabaseUrl}**/ventalis-jp_ordersdb
    username: ************
    password: ************

# JPA Configuration
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update # other options : none, validate ##for production##, update, create-drop ##DNU: for the FIRST init ONLY##
    properties:
      hibernate:
        show-sql: true # to see sql commands

# SQL Initialisation
  sql:
    init:
      mode: never # never ##for production##, embedded, always ##DNU: for the FIRST init ONLY##
      platform: mysql # specify the suffix of schema-{platform}.sql and data-{plateform}.sql files
